services:
  postgres:
    image: postgres:16
    container_name: pg_queue_container
    environment:
      POSTGRES_DB: queuedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_queue_data:/var/lib/postgresql/data

volumes:
  pg_queue_data:
